# TME 1

In [2]:
import numpy as np
#import pandas as pd
#dataset=pd.read_csv("BLOSUM62.txt")

## Part 1 :  Needleman & Wunsch

In [3]:
# Initialisation de l'alphabet
alphabet = ['A','T','G','C']

#Initialisation des valeurs de match, mismatch et gap
match = 1
mismatch = -2
gap = -1

#s1 et s2 sont les deux séquences utilisés pour notre test
s1 = "CATGAC"
s2 = "TCTGAAC"


In [5]:
def mat_dist(alphabet,match,mismatch):
    
    #Calcul de la longueur de l'alphabet
    l_al = len(alphabet)
    
    #Création de la matrice de distance
    mat = np.zeros((l_al,l_al))
    
    #Parcours sur deux dimensions
    for i in range(l_al):
        for j in range(l_al):
            #Attribution des valeurs de match et mismatch
            if(i==j):
                mat[i][j] = match
            else:
                mat[i][j]= mismatch
    return mat

In [6]:
#Calcul de matrice de distance pour atgc
mat = mat_dist(alphabet,match,mismatch)
print(mat)

[[ 1. -2. -2. -2.]
 [-2.  1. -2. -2.]
 [-2. -2.  1. -2.]
 [-2. -2. -2.  1.]]


In [7]:

# Calcul de matrice de score sans le traceback
def matscorewotb(s1,s2):
    
    #Initialisation de la matrice de score
    ms = np.zeros((len(s1)+1,len(s2)+1))
    
    #Récupération des longueurs pour l'itération
    x,y = ms.shape
    for i in range(1,y):
        ms[0][i] =i*gap
    for j in range(1,x):
        ms[j][0] =j*gap
    
    for i in range(1,x):
        for j in range(1,y):
            sig = 0
            if s1[i-1]==s2[j-1]:
                sig = match
            else :
                sig = mismatch
            
            v_diag = ms[i-1,j-1]+sig
            v_up = ms[i-1,j]+gap
            v_left = ms[i,j-1]+gap
            
            ms[i,j] = max([v_diag,v_up,v_left])
    return ms

print(matscorewotb(s1,s2))


[[ 0. -1. -2. -3. -4. -5. -6. -7.]
 [-1. -2.  0. -1. -2. -3. -4. -5.]
 [-2. -3. -1. -2. -3. -1. -2. -3.]
 [-3. -1. -2.  0. -1. -2. -3. -4.]
 [-4. -2. -3. -1.  1.  0. -1. -2.]
 [-5. -3. -4. -2.  0.  2.  1.  0.]
 [-6. -4. -2. -3. -1.  1.  0.  2.]]


In [61]:
# Calcul de matrice de score avec le traceback
def nw(s1,s2):
    
    #Initialisation de la matrice de score
    ms = np.zeros((len(s2)+1,len(s1)+1))
    Dir=[]
    #Récupération des longueurs pour l'itération
    x,y = ms.shape
    for i in range(len(ms)):
        for j in range(len(ms[i])):
            Dir.append([])
    Dir=np.array(Dir)
    Dir.reshape(8,7)
    print(ms.shape,Dir.shape)
    for i in range(1,x):
        ms[i][0] =-i
        Dir[i][0]=[1]
    for j in range(1,y):
        ms[0][j] =-j
        Dir[0][j]=[2]
    for i in range(1,x):
        for j in range(1,y):
            sig = 0
            if s2[i-1]==s1[j-1]:
                sig = match
            else :
                sig = mismatch
            #Traceback
            S=np.array([ms[i-1,j-1]+sig, ms[i-1,j]+gap, ms[i,j-1]+gap])
            ms[i,j]=max(S)
            index=list(np.where(S==max(S))[0])
            Dir[i][j]=index
    print(Dir)
    #En diagonale on remonte de la longueur de la séquence en ligne
    #En haut on remonte de diag -1
    #A gauche c'est évident
    sc1 = ""
    sc2 = "" 
    tbval = 0
    cell=len(Dir)-1
    nb1=len(s1)-1
    nb2=len(s2)-1
    while Dir[cell]!=[]:
        if 0 in Dir[cell]:
            sc1+=s1[nb1]
            sc2+=s2[nb2]
            nb1-=1
            nb2-=1
            cell-=(len(s2)+1)                           #on va vers cette cellule quand on a une diagonale (dans notre Traceback du moins)
        elif 1 in Dir[cell]:
            sc1+='_'
            sc2+=s2[nb2]
            nb2-=1
            cell-=(len(s2))                               #on va vers cette cellule quand on monte
        else:
            sc1+=s1[nb1]
            sc2+='_'
            nb1-=1
            cell-=1                                     #évident
    #sc1=sc1[::-1]
    #sc2=sc2[::-1]
    for c1 in range(len(sc1)):
            if sc1[c1] == sc2[c1]:
                tbval += match
            else :
                if (sc1[c1]=='_' or sc2[c1] == '_'):
                    tbval += gap
                else:
                    tbval +=mismatch
    return sc1,sc2,tbval


sc1,sc2,tbval = nw(s1,s2)
print(sc1)
print(sc2)
print(tbval)

ValueError: cannot reshape array of size 0 into shape (8,7)

In [34]:
s='abcdefghijklmnopqrstuvwxyz'
print(s[-25])
print(s[-1])

b
z


In [ ]:
   sc1 = ""
    sc2 = ""
    tb = []
    
    backx = x-1
    backy = y-1

    while not((backx==0 and backy==0)):
        v_diag = ms[backx-1,backy-1]
        v_left = ms[backx,backy-1]
        v_up = ms[backx-1,backy]
        

        backway = ""
        if v_diag > v_up:
            if v_diag> v_left:
                tb.append("d")
                sc1+=s1[backx-1]
                sc2+=s2[backy-1]
                backx-=1
                backy-=1
            else : 
                tb.append("l")
                sc1+='_'
                sc2+=s2[backy-1]
                backy-=1
        else:
            if v_up > v_left:
                tb.append("u")
                sc1+=s1[backx-1]
                sc2+='_'
                backx-=1
            else : 
                tb.append("l")
                sc1+='_'
                sc2+=s2[backy-1]
                backy-=1
        
    tbval = 0
    sc1 = sc1[::-1]         #permet d'inverser la chaine de caractères
    sc2 = sc2[::-1]
    
    for c1 in range(len(sc1)):
            if sc1[c1] == sc2[c1]:
                tbval += match
            else :
                if (sc1[c1]=='_' or sc2[c1] == '_'):
                    tbval += gap
                else:
                    tbval +=mismatch

## Part 2 : Petit exemple

In [32]:
test=np.array([1,1,0])
L=np.where(test==1)[0]
print(L)

[0 1]
