In [73]:
import numpy as np
import math
from numba import njit

In [62]:
matrix = np.array([[ -1  , 19, 27, 8 , 33, 18, 13 ],
                    [ 19, -1 , 31, 18, 36, 1 , 13 ],
                    [ 27, 31, -1 , 26, 41, 32, 29 ],
                    [ 8 , 18, 26, -1 , 31, 17, 14 ],
                    [ 33, 36, 41, 31, -1 , 35, 28 ],
                    [ 18, 1 , 32, 17, 35, -1 , 12 ],
                    [ 13, 13, 29, 14, 28, 12, -1 ],
                   ])

print( matrix.shape )

(7, 7)


In [63]:
with open('matrix.txt', 'w') as f:
    l1,l2 = matrix.shape
    for i in range(l1):
        string = ''
        for j in range(l2):
            string += str(matrix[i,j])+';'
        f.write(string.rstrip(';')+'\n')
    

In [64]:
m = np.genfromtxt("matrix.txt", delimiter=";")
print(m)

[[-1. 19. 27.  8. 33. 18. 13.]
 [19. -1. 31. 18. 36.  1. 13.]
 [27. 31. -1. 26. 41. 32. 29.]
 [ 8. 18. 26. -1. 31. 17. 14.]
 [33. 36. 41. 31. -1. 35. 28.]
 [18.  1. 32. 17. 35. -1. 12.]
 [13. 13. 29. 14. 28. 12. -1.]]


In [65]:
print(m)
print()
print(np.delete(m, 0, 1) )

[[-1. 19. 27.  8. 33. 18. 13.]
 [19. -1. 31. 18. 36.  1. 13.]
 [27. 31. -1. 26. 41. 32. 29.]
 [ 8. 18. 26. -1. 31. 17. 14.]
 [33. 36. 41. 31. -1. 35. 28.]
 [18.  1. 32. 17. 35. -1. 12.]
 [13. 13. 29. 14. 28. 12. -1.]]
()
[[19. 27.  8. 33. 18. 13.]
 [-1. 31. 18. 36.  1. 13.]
 [31. -1. 26. 41. 32. 29.]
 [18. 26. -1. 31. 17. 14.]
 [36. 41. 31. -1. 35. 28.]
 [ 1. 32. 17. 35. -1. 12.]
 [13. 29. 14. 28. 12. -1.]]


In [109]:


MIN = FindMin(m)
print(MIN)

(1, 5)


In [148]:
def FindMin(matrix):
    new_mat = np.where(matrix<0, 1000, matrix)
    return np.unravel_index(np.argmin(new_mat, axis=None), new_mat.shape)

def MatToNewick(nodes, weights, i, j):
    node_j = nodes.pop(j)
    node_i = nodes.pop(i)
    wj     = weights.pop(j)
    wi     = weights.pop(i)
    nodes.append( '({},{})'.format(node_i, node_j) )
    weights.append(wi+wj)
    return nodes, weights    

def MAJ(matrix, weights, i, j):
    # i < j on commence par enlever j puis i
    line_i = matrix[i,:]
    line_j = matrix[j,:]
    
    line_i = np.delete(line_i, j)
    line_i = np.delete(line_i, i)

    line_j = np.delete(line_j, j)
    line_j = np.delete(line_j, i)

    matrix = np.delete(matrix, j, 0)
    matrix = np.delete(matrix, i, 0)
    
    matrix = np.delete(matrix, j, 1)
    matrix = np.delete(matrix, i, 1)
    
    wi, wj = weights[i], weights[j]
    new_vect = (line_i*wi + line_j*wj) / (wi+wj) 
    
    matrix = np.vstack( (matrix,new_vect) )
    
    new_vect= np.hstack( (new_vect,[-1]) )
    
    return np.hstack( (matrix, new_vect.reshape(len(new_vect),1)))

def UPGMA(matrix):
    L = len(matrix)
    internal_nodes = 'abcdefghijklmnopqrstuvwxyz'
    mat_nodes = [internal_nodes[i] for i in range(L)]
    weights = [ 1 for i in range(L) ]
    
    while matrix.shape != (1,1):
        i, j = FindMin(matrix)
        if i < j:
            matrix = MAJ( matrix, weights, i, j )
            mat_nodes, weights = MatToNewick( mat_nodes, weights, i, j )

        else:
            matrix = MAJ( matrix, weights, j, i )
            mat_nodes, weights = MatToNewick( mat_nodes, weights, j, i )

    return matrix, mat_nodes, weights

In [149]:
res = UPGMA( m )
print(res)

(array([[-1.]]), ['(e,(c,((a,d),(g,(b,f)))))'], [7])


In [88]:
a = np.arange(10)
print(a)
print()
print(np.delete(a, 2))

[0 1 2 3 4 5 6 7 8 9]
()
[0 1 3 4 5 6 7 8 9]


In [147]:
a = 'abcdefghijklmnopqrstuvwxyz'
print(a[:5])
print(a[2:4])

abcde
cd


In [ ]:
string[:n]+string[k:]